proyect/config/routes.rb
Rails.application.routes.draw do

  resources :stores
  resources :products

  namespace :api do
    namespace :v1 do
      resources :stores, shallow:true do   #el shallow aplica a lo que esta debajo.
        resources :products
        resources :admins
      end
    end
  end
  
end

proyect/app/models/admin.rb
class Admin < ApplicationRecord
  belongs_to :store
  
end

proyect/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

proyect/app/models/product.rb
class Product < ApplicationRecord

  Product.connection
  belongs_to :store

  def self.muestralos
    response = RestClient.get'192.168.0.105:3000/products/index'
    @response = JSON.parse(response)
    return @response
  end

  # def server_search
  #   uri = URI.parse("http://localhost:3000/products")
  #   Net::HTTP::Get.index(uri.request_uri)request.set_form_data({"product[name]"})

  #   response = http.request(request)
  #   render :json => response.body
  # end
end

proyect/app/models/store.rb
class Store < ApplicationRecord
    has_many :products
    def self.muestralo
        response = RestClient.get'192.168.34.4:3000/stores'
        @response = JSON.parse(response)
        return @response
      end
  
end

proyect/app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def index
    @admin = Admin.all
  end
  http_basic_authenticate_with name: “admin”, password: “1234”, only: :index
  
  
  
  
   before_action :authenticate, only: :index
end

proyect/app/controllers/api/v1/admins_controller.rb
class Api::V1::AdminsController < ApplicationController
def index
@admins = Admin.all
render :json => @admins
end
end

proyect/app/controllers/api/v1/products_controller.rb
class Api::V1::ProductsController < ApplicationController
    def index 
        @products = Product.all
        render :json => @products
       end
       
       def show
       end
       
       def edit
    
       end
       
       def update
       
       end
       
       def new
        @product = Product.new
       end
       
       def create 
        @product = Product.new(product_params)
        if @product.save
          redirect_to product_path
        else
        render :new
       end
      end
       
       def destroy
       Product.find(params[:id]).delete
       render :json => Product.all
       end
    
     
    
       private
    
       def product_params
         params.require(:person).permit(:name, :image, :description, :price, :quantity, :store_id)
       end
end

proyect/app/controllers/api/v1/stores_controller.rb
class Api::V1::StoresController < ApplicationController
    http_basic_authenticate_with name: "admin", password: "secret", only: :index
    
    
    def index 

        @stores = Store.all
        render :json => @stores
       end
       
       def show
       end
       
      
       
       def update
       
       end
       
       def new
        @store = Store.new
       end
       
    #    def create 
    #     @store = Store.new(product_params)
    #     if @product.save
    #       redirect_to product_path
    #     else
    #     render :new
    #    end
    #   end
       
       def destroy
       Product.find(params[:id]).delete
       render :json => Product.all
       end
    
     
    
    #    private
    
    #    def product_params
    #      params.require(:person).permit(:name, :image, :description, :price, :quantity, :store_id)
    #    end
end

proyect/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

proyect/app/controllers/products_controller.rb
class ProductsController < ApplicationController

def index 
    @products = Product.muestralos
    # render json: @products
    end

   
end

proyect/app/controllers/stores_controller.rb
class   StoresController < ApplicationController
    
    def index 
        @stores = Store.muestralo
        render json: @stores
        end
    
       
    end

proyect/app/helpers/admins_helper.rb
module AdminsHelper
end

proyect/app/helpers/application_helper.rb
module ApplicationHelper
end

proyect/app/helpers/products_helper.rb
module ProductsHelper
end

proyect/app/helpers/stores_helper.rb
module StoresHelper
end

proyect/app/views/admins/index.html.haml
%h1 Admin Login
%br/

= form_with(model: @admin) do |form| 
    .field
        =form.label :Admin
        =form.text_field :name
    
    .field
        =form.label :password
        =form.text_field :password

    = form.submit

proyect/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proyect</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

proyect/app/views/products/index.html.haml
%h1.titulo1 Products
%table{border: 2}
  %tr
    %th Name
    %th Description
    %th Price
    %th Quantity
  - @products.each do |x|
    %tr
      %td= x['name']
      %td= x['description']
      %td= x['price']
      %td= x['quantity']

proyect/app/views/products/new.html.haml
%h1 Products

%br/

= form_with(model: [@store, @product] , local: true) do |form|
  .field
    = form.label :name
    = form.text_field :name
    .field
    = form.label :image
    = form.text_area :image
  .field
    = form.label :description
    = form.text_area :description
    .field
    = form.label :price
    = form.text_area :price
  .field
    = form.label :quantity
    = form.text_area :quantity
  .field 
    = form.hidden_field :store_id

  
    = form.submit

proyect/app/views/stores/index.html.haml
%h1.titulo1 Stores
%table
  %tr
    %th Name
    %th Category
  - @stores.each do |store|
    %tr
      %td= store.name
      
%br/
= link_to('Product', store_products_path(products_index_url))